const BUILDER = [
    MOVE,MOVE,MOVE,MOVE,MOVE,
    MOVE,MOVE,MOVE,MOVE,MOVE,
    MOVE,MOVE,MOVE,MOVE,MOVE,
    WORK,WORK,WORK,WORK,WORK,
    WORK,WORK,WORK,WORK,WORK,
    WORK,WORK,WORK,WORK,WORK,
    CARRY,CARRY,CARRY,CARRY,CARRY,
    CARRY,CARRY,CARRY,CARRY,CARRY,
    CARRY,CARRY,CARRY,CARRY,CARRY
];

const HAULER = [
    MOVE,MOVE,MOVE,MOVE,MOVE,
    MOVE,MOVE,MOVE,MOVE,MOVE,
    MOVE,MOVE,MOVE,
    CARRY,CARRY,CARRY,CARRY,CARRY,
    CARRY,CARRY,CARRY,CARRY,CARRY,
    CARRY,CARRY,CARRY,CARRY,CARRY,
    CARRY,CARRY,CARRY,CARRY,CARRY,
    CARRY,CARRY,CARRY,CARRY,CARRY,
    CARRY
];

const HARVESTER = [
    MOVE,
    WORK,WORK,WORK,WORK,WORK,
    CARRY
];

module.exports = {
    BUILDER,
    HAULER,
    HARVESTER
}